### PR TITLE
Quite some stuff

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
I know that there is a `dev` branch, but its CLI is not currently functioning... So, this PR targets the `main` branch.
If you want me to target the `dev` branch instead, I can also provide a PR doing that.

This PR changes the following things:
 - Update Gradle
 - Fix Gradle deprecations
 - Update JSON library
 - Add `lib/client` and `lib/server` folders where additional dependencies can be placed in which will also get added to the classpath
 - Trim command inputs (allow spaces in front of and after the command to evaluate)
 - Fix exiting using shortcuts like Ctrl+C
 - Fix obfuscation of custom packages (e.g., `de/XXX.class` was getting reobfuscated to `XXX.class` which is not what you want)
 - Fix errors and warnings without source files
 - Add `source`, `target`, and `bootclasspath` parameters to the recompile task
 - Fix erasing lines using a nice approach (the one before breaks if the console window is too small)
 - General cleanup for bad practices (and even some bugs!)

### CODE REVIEW

**Comment by Lassebq** [comment]
All seems to be good, although there's already `lib` folder, which serves the same purpose as `deps_client`. It could be split into `lib/client` and `lib/server` to contain dependencies for server too.

**Comment by ThexXTURBOXx** [comment]
@Lassebq Okay, I will change the paths accordingly.
Also, I have some more patches on my local machine which might be useful. I will push everything within the next hour.
Thanks for the review!

**Comment by ThexXTURBOXx** [comment]
@Lassebq This should now be everything I've got :)

**Comment by Lassebq** [comment]
Yep, seems good. I didn't know about eraseLine() btw, so thanks for fixing that.

**Pull request merged**
