### PR TITLE
Some things again

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
This PR fixes some warnings in the Java files and also within GitHub actions (see [here](https://github.com/MCPHackers/RetroMCP-Java/actions/runs/3387218960) for example).
Additionally, German translation has been updated and a small layout error inside the README has been corrected.

However, I should note that https://mcphackers.github.io/versions/versions.json is not properly formatted. It is neither an array nor do the entries contain an "id", "releaseTime" or similar fields. That's why the versions parser does not work right now.

### CODE REVIEW

**Comment by Lassebq** [comment]
> However, I should note that https://mcphackers.github.io/versions/versions.json is not properly formatted. It is neither an array nor do the entries contain an "id", "releaseTime" or similar fields. That's why the versions parser does not work right now.

I'm aware. The new versions.json format is not published yet to remain compatible with previous releases. A pre-release will probably fetch it from an alternative url, and only when the full release of 1.0 is out the json at https://mcphackers.github.io/versions/versions.json will be replaced with the new format

**Comment by ThexXTURBOXx** [comment]
Alright, I had something like that already in mind, thanks for clearing that up!

**Comment by Lassebq** [comment]
May I ask why the static modifier was removed from some inner enums? Are they static by default? And what about VALUES array? Why were values() calls replaced with it?

**Comment by ThexXTURBOXx** [comment]
Inner Enums are static by default. The modifiers/attributes I removed are also not needed.
The `VALUES` array is just a way of removing excessive calls to the `values()` function as it invokes some fairly complicated bytecode which can be reduced through a single call at initialization.
This only saves a small amount of performance in this case, but yeah... Better than nothing?

**Comment by Lassebq** [comment]
Oh, and what's up with the workflow file? Why did it fail?

**Comment by ThexXTURBOXx** [comment]
The new version needed an additional parameter which should have been applied from the beginning on. Didn't notice that it was not there before

**Comment by Lassebq** [comment]
Alright, thanks for the contribution, it's good to merge

**Pull request merged**
