### PR TITLE
Check your pull requests for the versions.json

### PR DESCRIPTION
**Pull request by CockAndBallTortureFromWikipediaTheFree**
do it

### CODE REVIEW

**Comment by Geolykt** [comment]
_why_

**Comment by CockAndBallTortureFromWikipediaTheFree** [comment]
It's possible to support more versions and would benefit the community. :smiley:

**Comment by Geolykt** [comment]
You do realize that github issues is a thing?

**Comment by CockAndBallTortureFromWikipediaTheFree** [comment]
I am the issue

**Pull request closed without merging**
